<?php
/**
 * Sample_News extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       Sample
 * @package        Sample_News
 * @copyright      Copyright (c) 2014
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
?>
<?php echo $this->getChildHtml() ?>
<div class="no-display">
    <input type="hidden" name="category_sample_news_articles" id="in_category_sample_news_articles" value=""/>
</div>
<?php if(($block = $this->getLayout()->getBlock('category.sample_news.article.grid')) && ($_gridJsObject = $block->getJsObjectName())): ?>
    <script type="text/javascript">
        require([
            "mage/adminhtml/grid"
        ], function(){
            var categorySampleNewsArticles = $H(<?php echo json_encode($block->getSelectedArticles()) ?>);
            $('in_category_sample_news_articles').value = Object.toJSON(categorySampleNewsArticles);

            function registerCategorySampleNewsArticle(grid, element, checked){
                if(checked){
                    if(element.positionElement){
                        element.positionElement.disabled = false;
                        categorySampleNewsArticles.set(element.value, element.positionElement.value);
                    }
                }
                else{
                    if(element.positionElement){
                        element.positionElement.disabled = true;
                    }
                    categorySampleNewsArticles.unset(element.value);
                }
                $('in_category_sample_news_articles').value = Object.toJSON(categorySampleNewsArticles);
                grid.reloadParams = {'category_sample_news_articles[]':categorySampleNewsArticles.keys()};
            }
            function categorySampleNewsArticleRowClick(grid, event){

                var trElement = Event.findElement(event, 'tr');
                var isInput   = Event.element(event).tagName == 'INPUT';
                if(trElement){
                    var checkbox = Element.getElementsBySelector(trElement, 'input');
                    if(checkbox[0]){
                        var checked = isInput ? checkbox[0].checked : !checkbox[0].checked;
                        <?php echo $_gridJsObject ?>.setCheckboxChecked(checkbox[0], checked);
                    }
                }
            }
            function sampleNewsArticlePositionChange(event){
                var element = Event.element(event);
                if(element && element.checkboxElement && element.checkboxElement.checked){
                    categorySampleNewsArticles.set(element.checkboxElement.value, element.value);
                    $('in_category_sample_news_articles').value = Object.toJSON(categorySampleNewsArticles);
                }
            }

            var tabIndex = 1000;
            function categorySampleNewsArticleRowInit(grid, row){
                var checkbox = $(row).getElementsByClassName('checkbox')[0];
                var position = $(row).getElementsByClassName('input-text')[0];
                if(checkbox && position){
                    checkbox.positionElement = position;
                    position.checkboxElement = checkbox;
                    position.disabled = !checkbox.checked;
                    position.tabIndex = tabIndex++;
                    Event.observe(position,'keyup',sampleNewsArticlePositionChange);
                }
            }


            <?php echo $_gridJsObject ?>.rowClickCallback = categorySampleNewsArticleRowClick;
            <?php echo $_gridJsObject ?>.initRowCallback = categorySampleNewsArticleRowInit;
            <?php echo $_gridJsObject ?>.checkboxCheckCallback = registerCategorySampleNewsArticle;
            <?php echo $_gridJsObject ?>.rows.each(function(row){
                categorySampleNewsArticleRowInit(<?php echo $_gridJsObject ?>, row)
            });
        });

    </script>
<?php endif;?>