<?php
/**
 * Sample_News extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       Sample
 * @package        Sample_News
 * @copyright      Copyright (c) 2014
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
?>
<?php $_sectionCollection = $this->getSectionCollection();?>
<?php if ($_sectionCollection->count() > 0) :?>
    <h2><?php echo __('Sections');?></h2>
    <div class="article-sections wrapper">
        <?php foreach($_sectionCollection as $_section) : ?>
            <a href="<?php echo $_section->getSectionUrl()?>"><?php echo $_section->getName();?></a><br />
        <?php endforeach;?>
    </div>
<?php endif;?>