<?php
/**
 * Sample_News extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       Sample
 * @package        Sample_News
 * @copyright      Copyright (c) 2014
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
?>
<?php $_articleCollection = $this->getArticleCollection();?>
<?php if ($_articleCollection->count() > 0) :?>
    <h2><?php echo __('Articles');?></h2>
    <div class="section-articles wrapper">
        <?php foreach($_articleCollection as $_article) : ?>
            <a href="<?php echo $_article->getArticleUrl()?>"><?php echo $_article->getTitle();?></a><br />
        <?php endforeach;?>
    </div>
<?php endif;?>