<?php $_sections = $this->getSections(); ?>
<?php if ($_sections->getSize() > 0) :?>
    <div class="page-title news-section-title">
        <h2><?php echo $this->getCurrentSection()->getName(); ?>:<?php echo __('Child Sections')?></h2>
    </div>
    <?php if ($this->getDisplayMode() == 0) : ?>
        <div class="section-list-container">
            <?php foreach ($_sections as $_section) : ?>
            <div class="section-list-item">
                <a href="<?php echo $_section->getSectionUrl();?>" title="<?php echo $this->escapeHtml($_section->getName()) ?>">
                    <?php echo $_section->getName(); ?>
                </a>
            </div>
            <?php endforeach;?>
        </div>
    <?php else : ?>
        <ul id="sections-list">
            <?php foreach ($_sections as $_section) : ?>
                <?php echo $this->drawSection($_section);?>
            <?php endforeach;?>
        </ul>
        <script type="text/javascript">
            require([
                "jquery",
                "jquery/ui",
                "Sample_News/js/tree"
            ], function(){
                jQuery('#sections-list').treeDisplay();
            });
        </script>
    <?php endif;?>
<?php endif;?>
