<?php
/**
 * Sample_News extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       Sample
 * @package        Sample_News
 * @copyright      Copyright (c) 2014
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
?>
<div class="categories-side-col">
    <div class="sidebar-actions">
        <?php echo $this->getAddRootButtonHtml() ?><br/>
        <?php echo $this->getAddSubButtonHtml() ?>
    </div>
    <div class="tree-actions">
        <a href="#" onclick="tree.collapseTree(); return false;"><?php echo __('Collapse All'); ?></a>
        <span class="separator">|</span>
        <a href="#" onclick="tree.expandTree(); return false;"><?php echo __('Expand All'); ?></a>
    </div>
<?php if ($this->getRoot()): ?>
    <div class="tree-holder">
        <div id="tree-div" style="width:100%; overflow:auto;"></div>
    </div>
</div>
<script type="text/javascript">
var tree;
require(["jquery", "prototype", "mage/adminhtml/form"], function(jQuery){

/**
 * Fix ext compatibility with prototype 1.6
 */
Ext.lib.Event.getTarget = function (e) {
    var ee = e.browserEvent || e;
    return ee.target ? Event.element(ee) : null;
};

Ext.tree.TreePanel.Enhanced = function (el, config) {
    Ext.tree.TreePanel.Enhanced.superclass.constructor.call(this, el, config);
};

Ext.extend(Ext.tree.TreePanel.Enhanced, Ext.tree.TreePanel, {

    loadTree:function (config, firstLoad) {
        var parameters = config['parameters'];
        var data = config['data'];

        if ((typeof parameters['root_visible']) != 'undefined') {
            this.rootVisible = parameters['root_visible'] * 1;
        }

        var root = new Ext.tree.TreeNode(parameters);

        this.nodeHash = {};
        this.setRootNode(root);

        if (firstLoad) {
            this.addListener('click', this.sectionClick);
            this.addListener('beforenodedrop', sectionMove.createDelegate(this));
        }

        this.loader.buildSectionTree(root, data);
        this.el.dom.innerHTML = '';
        // render the tree
        this.render();
        if (parameters['expanded']) {
            this.expandAll();
        } else {
            root.expand();
        }

        var selectedNode = this.getNodeById(parameters['section_id']);
        if (selectedNode) {
            this.currentNodeId = parameters['section_id'];
        }
        this.selectCurrentNode();

        // Temporary solution will be replaced after refactoring of tree functionality
        jQuery('body').off('tabsactivate.tree').on('tabsactivate.tree', jQuery.proxy(function (e, ui) {
            this.activeTab = jQuery(ui.newTab).find('a').prop('id');
        }, this))
    },

    request:function (url, params) {
        if (!params) {
            if (this.activeTab) {
                var params = {active_tab_id:this.activeTab};
            }
            else {
                var params = {};
            }
        }
        if (!params.form_key) {
            params.form_key = FORM_KEY;
        }
        var result = new Ajax.Request(
                url + (url.match(new RegExp('\\?')) ? '&isAjax=true' : '?isAjax=true' ),
                {
                    parameters:params,
                    method:'post'
                }
        );

        return result;
    },

    selectCurrentNode:function () {
        if (this.currentNodeId) {
            var selectedNode = this.getNodeById(this.currentNodeId);
            if ((typeof selectedNode.attributes.path) != 'undefined') {
                var path = selectedNode.attributes.path;
                this.selectPath(path);
            } else {
                this.getSelectionModel().select(selectedNode);
            }
        }
    },

    collapseTree:function () {
        this.collapseAll();

        this.selectCurrentNode();

        if (!this.collapsed) {
            this.collapsed = true;
            this.loader.dataUrl = '<?php echo $this->getLoadTreeUrl(false) ?>';
            this.request(this.loader.dataUrl, false);
        }
    },

    expandTree:function () {
        this.expandAll();
        if (this.collapsed) {
            this.collapsed = false;
            this.loader.dataUrl = '<?php echo $this->getLoadTreeUrl(true) ?>';
            this.request(this.loader.dataUrl, false);
        }
    },

    sectionClick:function (node, e) {
        var baseUrl = '<?php echo $this->getEditUrl() ?>';
        var urlExt = 'id/' + node.id + '/';
        var url = parseSidUrl(baseUrl, urlExt);

        this.currentNodeId = node.id;
        if (!this.useAjax) {
            setLocation(url);
            return;
        }
        if (this.activeTab) {
            var params = {active_tab_id:this.activeTab};
        }
        updateContent(url, params);
    }
});

function reRenderTree() {
    if (tree) {
        var url;
        if ($('add_root_section_button')) {
            $('add_root_section_button').show();
        }

        if (tree.useAjax) {
            // retain current selected section id
            url = tree.switchTreeUrl + 'id/' + tree.currentNodeId + '/';
            // load from cache
            // load from ajax
            // add form key
            var params = {
                form_key : FORM_KEY
            };
            new Ajax.Request(url + (url.match(new RegExp('\\?')) ? '&isAjax=true' : '?isAjax=true' ), {
                parameters:params,
                method:'post',
                onComplete:function (transport) {
                    var response = eval('(' + transport.responseText + ')');
                    if (!response['parameters']) {
                        return false;
                    }

                    _renderNewTree(response, switcherParams.scopeParams);
                }
            });
        } else {
            var baseUrl = '<?php echo $this->getEditUrl() ?>';
            var urlExt = switcherParams.scopeParams + 'id/' + tree.currentNodeId + '/';
            url = parseSidUrl(baseUrl, urlExt);
            setLocation(url);
        }
    }
    // render default tree
    else {
        _renderNewTree();
    }
}

function _renderNewTree(config, scopeParams) {
    if (!config) {
        var config = defaultLoadTreeParams;
    }
    if (tree) {
        tree.purgeListeners();
        tree.el.dom.innerHTML = '';
    }
    tree = new Ext.tree.TreePanel.Enhanced('tree-div', newTreeParams);
    tree.loadTree(config, true);

    // try to select current section
    var selectedNode = tree.getNodeById(config.parameters.section_id);
    if (selectedNode) {
        tree.currentNodeId = config.parameters.section_id;
    }
    tree.selectCurrentNode();

    // update content area
    var url = tree.editUrl;
    if (scopeParams) {
        url = url + scopeParams;
    }
    <?php if ($this->isClearEdit()): ?>
        if (selectedNode) {
            url = url + 'id/' + config.parameters.section_id;
        }
        <?php endif;?>
    //updateContent(url); //commented since ajax requests replaced with http ones to load a section
}

Ext.onReady(function () {
    sectionLoader = new Ext.tree.TreeLoader({
        dataUrl:'<?php echo $this->getLoadTreeUrl() ?>'
    });

    sectionLoader.createNode = function (config) {
        var node;
        var _node = Object.clone(config);
        if (config.children && !config.children.length) {
            delete(config.children);
            node = new Ext.tree.AsyncTreeNode(config);
        } else {
            node = new Ext.tree.TreeNode(config);
        }

        return node;
    };

    sectionLoader.buildSectionTree = function (parent, config) {
        if (!config) return null;

        if (parent && config && config.length) {
            for (var i = 0; i < config.length; i++) {
                var node;
                var _node = Object.clone(config[i]);
                if (_node.children && !_node.children.length) {
                    delete(_node.children);
                    node = new Ext.tree.AsyncTreeNode(_node);
                } else {
                    node = new Ext.tree.TreeNode(config[i]);
                }
                parent.appendChild(node);
                node.loader = node.getOwnerTree().loader;
                if (_node.children) {
                    this.buildSectionTree(node, _node.children);
                }
            }
        }
    };

    sectionLoader.buildHash = function (node) {
        var hash = {};

        hash = this.toArray(node.attributes);

        if (node.childNodes.length > 0 || (node.loaded == false && node.loading == false)) {
            hash['children'] = new Array;

            for (var i = 0, len = node.childNodes.length; i < len; i++) {
                if (!hash['children']) {
                    hash['children'] = new Array;
                }
                hash['children'].push(this.buildHash(node.childNodes[i]));
            }
        }

        return hash;
    };

    sectionLoader.toArray = function (attributes) {
        var data = {form_key:FORM_KEY};
        for (var key in attributes) {
            var value = attributes[key];
            data[key] = value;
        }

        return data;
    };

    sectionLoader.on("beforeload", function (treeLoader, node) {
        treeLoader.baseParams.id = node.attributes.id;
        treeLoader.baseParams.form_key = FORM_KEY;
    });

    sectionLoader.on("load", function (treeLoader, node, config) {
        varienWindowOnload();
    });

    newTreeParams = {
        animate:false,
        loader:sectionLoader,
        enableDD:true,
        containerScroll:true,
        selModel:new Ext.tree.CheckNodeMultiSelectionModel(),
        rootVisible:'<?php echo $this->getRoot()->getIsVisible() ?>',
        useAjax: <?php echo $this->getUseAjax() ?>,
        switchTreeUrl:'<?php echo $this->getSwitchTreeUrl() ?>',
        editUrl:'<?php echo $this->getEditUrl() ?>',
        currentNodeId: <?php echo (int)$this->getSectionId() ?>
    };

    defaultLoadTreeParams = {
        parameters:{
            text:'<?php echo htmlentities($this->getRoot()->getName()) ?>',
            draggable:false,
        allowDrop   : <?php if ($this->getRoot()->getIsVisible()): ?>true<?php else : ?>false<?php endif; ?>,
            id: <?php echo (int)$this->getRoot()->getId() ?>,
            expanded: <?php echo (int)$this->getIsWasExpanded() ?>,
            section_id: <?php echo (int)$this->getSectionId() ?>
        },
        data: <?php echo $this->getTreeJson() ?>
    };

    reRenderTree();
});

function addNew(url, isRoot) {
    if (isRoot) {
        tree.currentNodeId = tree.root.id;
    }

    url += 'parent/' + tree.currentNodeId;
    updateContent(url);
}

function sectionMove(obj) {
    var data = {id:obj.dropNode.id, form_key:FORM_KEY};

    data.point = obj.point;
    switch (obj.point) {
        case 'above' :
            data.pid = obj.target.parentNode.id;
            data.paid = obj.dropNode.parentNode.id;
            if (obj.target.previousSibling) {
                data.aid = obj.target.previousSibling.id;
            } else {
                data.aid = 0;
            }
            break;
        case 'below' :
            data.pid = obj.target.parentNode.id;
            data.aid = obj.target.id;
            break;
        case 'append' :
            data.pid = obj.target.id;
            data.paid = obj.dropNode.parentNode.id;
            if (obj.target.lastChild) {
                data.aid = obj.target.lastChild.id;
            } else {
                data.aid = 0;
            }
            break;
        default :
            obj.cancel = true;
            return obj;
    }

    var success = function (o) {
        try {
            if (o.responseText) {
                if (o.responseText === 'SUCCESS') {
                    jQuery(obj.tree.container.dom).trigger('sectionMove.tree');
                } else {
                    alert(o.responseText);
                    location.reload();
                }
            }
        }
        catch (e) {
        }
    };

    var failure = function (o) {
        if (window.console) {
            console.log(o.statusText);
        } else {
            alert(o.statusText);
        }
        location.reload();
    };

    var pd = [];
    for (var key in data) {
        pd.push(encodeURIComponent(key), "=", encodeURIComponent(data[key]), "&");
    }
    pd.splice(pd.length - 1, 1);
    new Ajax.Request(
            '<?php echo $this->getMoveUrl() ?>',
            {
                method:'POST',
                parameters:pd.join(""),
                onSuccess:success,
                onFailure:failure
            }
    );
}

    window.addNew = addNew;

});
</script>
<?php endif; ?>
