<?php
/**
 * Sample_News extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       Sample
 * @package        Sample_News
 * @copyright      Copyright (c) 2014
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
?>
<?php $_categoryCollection = $this->getCategoryCollection();?>
<?php if ($_categoryCollection->count() > 0) :?>
    <h2><?php echo __('Categories');?></h2>
    <div class="article-categories wrapper">
        <?php foreach($_categoryCollection as $_category) : ?>
            <a href="<?php echo $_category->getUrl()?>"><?php echo $_category->getName();?></a><br />
        <?php endforeach;?>
    </div>
<?php endif;?>