<?php /** @var \Sample\News\Block\Author\ViewAuthor $this */?>
<?php /** @var \Sample\News\Model\Author $_author */?>
<?php $_author = $this->getCurrentAuthor();?>
<div class="author-view">
    <div class="author-name">
        <?php echo __('Name') ?>: <?php echo $_author->getName();?>
    </div>
    <?php //TODO: handle WYSIWYG attributes differently ?>
    <div class="author-biography">
        <?php echo __('Biography') ?>: <?php echo $_author->getBiography();?>
    </div>
    <div class="author-dob">
        <?php echo __('Date of birth') ?>: <?php echo $this->formatDate($_author->getDob(), \IntlDateFormatter::LONG);?>
    </div>
    ...
</div>
