<?php /** @var \Sample\News\Block\Catalog\Category\ListAuthor $this */?>
<?php $_authors = $this->getAuthorCollection();?>
<?php if ($_authors && $_authors->count() > 0) :?>
<div class="block-content content" id="<?php echo $this->getAnchorName();?>">
    <h2><?php echo __('Authors')?></h2>
    <div><?php echo $this->getPagerHtml();?></div>
    <?php /** @var \Sample\News\Model\Author $_author */?>
    <?php foreach ($_authors as $_author) : ?>
        <div class="item">
            <a href="<?php echo $_author->getAuthorUrl();?>"><?php echo $_author->getName();?></a>
        </div>
    <?php endforeach; ?>
    <div><?php echo $this->getPagerHtml();?></div>
</div>
<?php endif;?>
