<?php
/**
 * Sample_News extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       Sample
 * @package        Sample_News
 * @copyright      Copyright (c) 2014
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
?>
<?php $sections = $this->getSectionCollection();?>
<?php if ($sections && $sections->count() > 0) :?>
<div class="block-content content">
    <h2><?php echo __('Sections')?></h2>
    <?php /** @var \Sample\News\Model\Section $_section */?>
    <?php foreach ($sections as $_section) : ?>
        <div class="item">
            <a href="<?php echo $_section->getSectionUrl();?>"><?php echo $_section->getName();?></a>
        </div>
    <?php endforeach; ?>
</div>
<?php endif;?>
