<?php /** @var \Sample\News\Block\Author\ViewAuthor\Catalog\Category $this */?>
<?php $_categoryCollection = $this->getCategoryCollection();?>
<?php if ($_categoryCollection->count() > 0) :?>
    <div class="sample-news-authors-toolbar toolbar top"><?php echo $this->getPagerHtml(); ?></div>
    <div class="author-categories wrapper">
        <?php foreach($_categoryCollection as $_category) : ?>
            <?php /** @var \Magento\Catalog\Model\Category $_category */?>
            <a href="<?php echo $_category->getUrl()?>"><?php echo $_category->getName();?></a><br />
        <?php endforeach;?>
    </div>
    <div class="sample-news-authors-toolbar toolbar top"><?php echo $this->getPagerHtml(); ?></div>
<?php endif;?>
